---
title: "Введение"
subtitle: "Визуализация и анализ географических данных на языке R"
author: "Тимофей Самсонов"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, "style.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Структура курса

1. Основы программирования на R
2. Графика и статистика
3. Пространственные данные и карты
4. Пространственная статистика

В каждом разделе по 4 темы, итого 16 тем

---

## Формы отчетности

1. Домашние работы по каждой теме, кроме двух последних (14 работ)
2. Тесты по каждому разделу (4 теста)
3. Творческое задание (придумать не позднее 1 декабря)

---

## Условия зачета по курсу

__Общие требования:__

- Все работы (включая творческую) должны быть сданы и приняты преподавателем с оценкой не ниже 1.
- Минимум половина работ должна иметь оценку 2.
- Все 4 теста должны быть написаны на уровне не ниже 60%

__Требования к сдаче работ:__

- Каждая работа сдается в течение __недели__ после занятия по соответствующей теме (со вторника по понедельник)
- В дальнейшем есть возможность исправить работу по замечаниям

---

## Еженедельный цикл обучения

__В классе:__

1. Прослушать краткий обзор сегодняшней темы
2. Выполнить контрольные упражнения вместе с преподавателем (__без отчетности__)

__Дома:__

3. Выполнить и отправить на проверку домашнее задание по _текущей_ теме
4. Исправить замечания по _предыдущим_ работам
5. Внимательно прочитать главу пособия по _предстоящей_ теме

---

## Почему R?

1. Единственный широко распространённый язык программирования, __разработанный для целей анализа данных__.

1. Мощный и выразительный синтаксис. Код, решающий сложные задачи, может быть удивительно компактным.

1. Огромное сообщество специалистов, горячо любящих этот язык и постоянно улучшающих его функциональность

1. Более 10 000 библиотек для самых разнообразных задач. Все инновации в области Data Science быстро появляются в R.

1. Широкая поддержка пространственных данных.