# Круговая статистика и визуализация {#spatial_data}

```{r setup, echo = FALSE, purl = FALSE, cache = FALSE, include=FALSE}
library(DT)
knitr::opts_knit$set(global.par = TRUE)
knitr::opts_knit$set(root.dir = "data/")
knitr::opts_chunk$set(warning=FALSE, collapse = TRUE)
```

[Программный код главы](https://github.com/tsamsonov/r-geo-course/blob/master/code/07-SpatialData.R)

Обработкой данных о направлениях занимается особая область математической статистики — статистика направлений, или круговая (циркулярная) статистика (Mardia, Jupp, 2000; Pewsey et al., 2013). В круговой статистике каждое направление θ представляется в виде вектора x=(cosaθ,sinaθ ). Все операции производятся над векторами и их координатами. Аналогом нормального распределения для круговой случайной величины является распределение фон Мизеса (von Mises, 1918), которое задается функцией плотности вероятности:
f(θ)=1/(2πI_0 (κ)) e^(κ cosa〖(θ-μ)〗 ),
где κ≥0 — параметр концентрации, μ — среднее значение (для κ>0) и 
I_p (κ)=1/2π ∫_0^2π▒〖cosa〖pθe^(κ cosaθ ) 〗 □(24&dθ)〗
есть модифицированная функция Бесселя первого рода и порядка p. Из формул видно, что по своему эффекту параметр концентрации противоположен среднеквадратическому отклонению σ, которое является параметром нормального распределения. Чем больше значение κ, тем более сконцентрировано распределение относительно среднего значения — отсюда идет название этого параметра. Распределение фон Мизеса будет нами использовано далее при вычислении основных направлений каньонов методом ядерной оценки плотности распределения.
Для вычисления статистических моментов круговой случайной величины требуется найти средний равнодействующий вектор первого порядка R=(C,S), где C=1/n ∑_(j=1)^n▒cosa〖〖 θ〗_j 〗 ,S=1/n ∑_(j=1)^n▒sina〖θ_j 〗 . Данный вектор имеет направление ¯θ, которое является выборочным средним направлением исследуемой величины. Выборочная средняя равнодействующая длина ¯R=√(C^2+S^2 ) принимает значения в диапазоне [0,1] и показывает меру концентрации направлений относительно ¯θ. ¯R=1 означает, что все исходные направления совпадают, ¯R=0 — что данные равномерно распределены по кругу, либо распределение имеет несколько мод, которые уравновешивают друг друга. Стандартное отклонение направлений v в радианах может быть найдено как v=√(-2 lna¯R ) (Mardia, Jupp, 2000).
Величина ¯R дает важную информацию для предварительной диагностики картины направлений каньонов. Если значение ¯R близко к единице, это означает, что распределение является унимодальным и в качестве основного направления каньона можно принять значение ¯θ. На практике, однако, такая ситуация в городах достаточно редка, поскольку для каждого выбранного участка характерно как минимум две моды направлений каньонов, что требует их явного выделения статистическими методами.
Данные о направлениях каньонов специфичны, поскольку противоположные направления эквивалентны. Такие данные в теории круговой статистики называются аксиальными (Mardia, Jupp, 2000). Для аксиальных данных возможный диапазон значений лежит в интервале [0,π). Поскольку методы круговой статистики рассчитаны на круговое замыкание данных, стандартный подход к обработке аксиальных данных предполагает переход от направлений к их удвоенным значениям θ^'=2θ, обработку полученных значений стандартными методами и отображение полученных значение обратно на интервал [0,π). Для среднего, медианы и моды распределения это означает простое деление полученного значения пополам (Pewsey et al., 2013).
