project:
  type: book
  output-dir: docs
  
execute: 
  warning: false
  error: false
  message: false

book:
  title: "Визуализация и анализ географических данных на языке R"
  author: "Тимофей Самсонов"
  date: today
  chapters:
    - index.qmd
    - part: "Основы"
      chapters: 
        - 01-Basics.qmd
        - 02-DataStructures.qmd
        - 03-Tables.qmd
        - 04-Functions.qmd
    - part: "Графика и статистика"
      chapters: 
        - 05-BaseGraphics.qmd
        - 06-AdvGraphics.qmd
        - 07-BaseStats.qmd
        - 08-AdvStats.qmd
    - part: "Пространственные данные и карты"
      chapters: 
        - 09-SpatialData.qmd
        - 10-Maps.qmd
        - 11-ThematicMaps.qmd
        - 12-3DModels.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

