project:
  type: book
  output-dir: docs

book:
  title: "Визуализация и анализ географических данных на языке R"
  author: "Тимофей Самсонов"
  date: today
  chapters:
    - index.qmd
    - part: "Основы"
      chapters: 
        - 01-Basics.qmd
        - 02-DataStructures.qmd
        - 03-Tables.qmd
        - 04-Functions.qmd
    - part: "Графика и статистика"
      chapters: 
        - 05-BaseGraphics.qmd
        - 06-AdvGraphics.qmd
        - 07-BaseStats.qmd
        - 08-AdvStats.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

