---
title: "Геостатистика"
subtitle: "Пространственная статистика"
author: "Тимофей Самсонов"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, "style.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

## Базовые компоненты

1. Пространственные локации (точки)
  $$\{p_1, p_2, ..., p_n\}$$
2. Данные в этих локациях
  $$\{Z(p_1), Z(p_2), ..., Z(p_n)\}$$
> Обе компоненты в общем случае являются случайными

---

## Пространственная модель

$p \in \mathbb{R}^k$ --- точка в $k$-мерном Евклидовом пространстве
$Z(p)$ --- __случайная величина__ в точке $p$

Если $p$ меняется над индексным множеством $D \subset \mathbb{R}^k$, то формируется __случайный процесс__:

$$\{Z(p) | p \in D\}$$
Результат наблюдения случайного процесса в точках $D$ является __реализацией__ случайного процесса:

$$\{z(p) | p \in D\}$$
> В общем случае $D$ и $Z$ предполагаются случайными и независимыми друг от друга

---

## Случайный процесс (функция)

> __Случайный процесс__ --- это семейство случайных величин, индексированных некоторым параметром $t$

- Наиболее часто анализируются одномерные случайные процессы, в которых $t$ --- это время

- Пространственная статистика изучает случайные процессы, в которых $t$ — это координата точки (обычно на плоскости)

- В каждой точке существует некоторая _случайная величина_ — __сечение случайного процесса__

---

## Пространственная статистика

1. __Геостатистика__ _(geostatistics)_
  - $D$ --- фиксированное подмножество в $\mathbb{R}^k$
  - $Z(p)$ --- случайный вектор в каждой точке $p$
  - Исследуется пространственное распределение
2. __Сеточные данные__ _(lattice data)_
  - $D$ --- фиксированное счетное подмножество точек $\mathbb{R}^k$
  - $Z(p)$ --- случайный вектор в каждой точке $p$
  - Исследуется пространственная автокорреляция
3. __Конфигурации точек__ _(point patterns)_
  - $D$ --- счетное подмножество точек $\mathbb{R}^k$ _(точечный процесс)_
  - $Z(p)$ --- константа или счетное множество _(маркированный точечный процесс)_
  - Исследуется пространственное размещение