---
title: "Untitled"
output: html_document
---

В статистике моделирование данных, обладающих автокорреляцией, осуществаляется с помощью авторегрессионных моделей (AR-моделей). Авторегрессионная модель связывает значения временного ряда в данный момент с предыдущими значениями этого же ряда. В пространственной статистике используется аналогичная методика, только в роли данного момента выступает данная территориальная единица, а в роли предыдущих значений — значения в соседних территориальных единицах (см. презентацию). После того как параметры пространственной авторегрессии подобраны, можно вычислить значение в каждой единице по соседним значениям, а также ошибку полученного значения путем вычитания из реального значения.

Простейшая модель пространственной авторегрессии строится как:
$$
Z = \mu + \sum b(z-\mu) + \epsilon
$$
где $Z$ - значение в текущей единице, $z$ - значение в соседней единице, $\mu$ — среднее значение (вычисленное по всем единицам), $b$ - весовой коэффициент и $ε$ — случайная ошибка. 

Подобное уравнение может быть составлено для каждой территориальной единицы. При этом суммирование производится по всем соседним территориальным единицам а неизвестный коэффициент $b$ обычно представляют в виде $b = \lambda w$, то есть как отмасштабированный на величину $\lambda$ вес связи между единицей и ее текущим соседом. Задача построения модели строится к поиску такого значения $\lambda$, который бы минимизировал сумму квадратов ошибок ε по всем территориальным единицам.

Если мы знаем, что в каждой единице значение связано не только с окружением, но также с другой величиной, то это можно моделировать заменив в вышеприведенном уравнении $\mu$ на $a + bY$, где $Y$ — объясняющая величина, а коэффициенты $a$ и $b$ подбираются путем построения линейной регрессии между $Z$ и $Y$.

Для построения модели пространственной авторегрессии используется функция `spautolm()`, принимающая два основных параметра — формулу и матрицу пространственных весов. Формула — это специальный объект __R__ для обозначения статистической зависимости. Например, если в таблице `tab` есть столбец `Z`, зависящий от `X` и `Y`, то соответствующая формула будет выглядеть следующим образом:
```
Z ~ X + Y
```

В случае если зависимости нет, используется следующая нотация:
```
Z ~ 1
```

Мы будем использовать простейший вариант пространственной авторегрессии без объясняющих факторов $(Z = \mu + \sum \lambda w(z-\mu) + \epsilon)$. Следовательно, используем вариант `~1`